### ISSUE TITLE
Steps get carried over to the next day if phone is off at midnight

### ISSUE THREAD

**Issue by columndeeply** [0xf4b1/motionmate#71]
Hi! I've started using the app a few days ago and so far its great but I've noticed that if my phone is off at midnight the steps I did that day get added to the next day.

Here is an example, this is what I did on the last three days (all numbers are approximates, I don't have the real count for the first two days. I do know there were steps registered on the 08/02/22 tho):
- 08/02/22 ~ 1.500 steps
- 08/03/22 ~ 10.000 steps
- 08/04/22 ~ 134 steps

But on the app it's recorded like this:
![image](https://user-images.githubusercontent.com/106948293/182784386-57ee8fb9-7e2b-48b6-8e06-899f058222b7.png)

On Tuesday night I turned my phone off, when I opened it next day those 1.500 steps were set to "Wednesday". Just to make sure that was the cause, I didn't power if off on Wednesday night. Then it worked fine, it stopped counting and started from zero on Thursday.

I'm using the 1.3.3 release, downloaded from the IzzyOnDroid repo on the 08/02/22:
![image](https://user-images.githubusercontent.com/106948293/182786756-e63e20c4-11c6-4f3e-8a77-535bc322e960.png)

Many thanks for the app again!

**Comment by 0xf4b1** [comment]
Hey, thank you for the report, I'll check this.

**Comment by columndeeply** [comment]
Hi! I've been playing with this again and it seems to be working properly now... Not sure what I did that first day to break it but now even if the phone is off everything gets recorded properly.

I'll reopen this issue if I figure out what I did the to break it that first time.

Thanks!
