### ISSUE TITLE
Incorrect calendar

### ISSUE THREAD

**Issue by KolyaKorruptis** [0xf4b1/motionmate#78]
According to motionmate October 2023 has only 29 days.
Today is the 31. October 2023. 
My clock and other calendar apps show the correct date.
MotionMate version 1.3.3-release

![image](https://github.com/0xf4b1/motionmate/assets/4076947/9d08766f-b1e3-40cf-b7a5-15e679a029fc)

**Comment by 0xf4b1** [comment]
Hey, this is a layout issue, the lower part of the calendar is cut off. I'll fix it in the next release.

**Comment by KolyaKorruptis** [comment]
Confirmed fix.

**Comment by 0xf4b1** [comment]
Thank you :)
