### ISSUE TITLE
Data import and export

### ISSUE THREAD

**Issue by 2fsbb9op** [0xf4b1/motionmate#81]
I've been using [https://gitlab.com/pardomi/paseo](url) for many years but, I've always found the interface a little busy/confusing.  Paseo exports data in *.db files vs *.csv files.

I looked at the Motionmate *.csv file thinking I might manually enter **some** of the data from Paseo and import.  Am I correct in assuming the first column is a Unix Timestamp and the second column is the number of steps?

**Comment by 2fsbb9op** [comment]
I tried to convert the Paseo db file to a csv file without success.  I also tried to manually manipulate the csv file exported from Motionmate and then import it but, that also didn't work.

Perhaps in a future release, a long press on a date with an option to manually enter steps as a possible solution (when migrating from a different pedometer).

**Comment by 0xf4b1** [comment]
> Am I correct in assuming the first column is a Unix Timestamp and the second column is the number of steps?

Yes you are right, its actually as simple as that. The timestamps are aligned to the start of the day and there should only be one entry that corresponds to a single day.

> I also tried to manually manipulate the csv file exported from Motionmate and then import it but, that also didn't work.

Manipulating the csv file should actually be not a problem, so it should be easily possible to get other data into the app
